spring.application.name=TodoList
spring.datasource.url=jdbc:postgresql://localhost:5433/todo_list
spring.datasource.username=postgres
spring.datasource.password=1111

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Telegram

telegram.bot.token=${BOT_TOKEN}
telegram.bot.username=${BOT_NAME}